on:
  push:
    branches:
      - master

name: release-please

permissions: read-all

jobs:
  release-please:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
